### ISSUE TITLE
knn error

### ISSUE THREAD

**Issue by carlzimmerman** [dansbits/lurn#15]
maybe im doing something wrong but im getting this when i put the following command in the concole:

model = Lurn::Neighbors::KNNRegression.new(2)

NameError: uninitialized constant Lurn::Neighbors
	from (irb):13

**Comment by carlzimmerman** [comment]
nvm... had to add  github: 'dansbits/lurn' to the gem 'lurn' in the gemfile

**Comment by dansbits** [comment]
Sorry for the confusion. As you realized KNN isn't in the release on rubygems at the moment. I'll try to get that out soon.

**Comment by carlzimmerman** [comment]
I was able to get KNN working.. the rails console only let me dump a certain about of data into it so im going through your other tutorial to reference a data file.

**Comment by dansbits** [comment]
Glad you got it running! What was the error with the rails console?

If you run into major performance or operational issues please let me know. If optimizations need to be made I'd love to hear about it.
