### ISSUE TITLE
Wrong variable in comment on documentation

### ISSUE THREAD

**Issue by v3nd3774** [dansbits/lurn#19]
Looks like the this line:
```
# extract annual income
target_var = people.map { |person| person[2]}
```
should be changed to:
```
# extract job title
target_var = people.map { |person| person[2]}
```
In the documentation [here](https://github.com/dansbits/lurn/blob/master/readmes/neighbors/knn_classification.md).

**Comment by dansbits** [comment]
@v3nd3774 I just merged your PR. Closing this issue. Thanks!
